### ISSUE TITLE
Optional inline Type

### ISSUE THREAD

**Issue by ghost** [DorsetDigital/silverstripe-enhanced-requirements#5]
Can you make the "type" attribute optional for inline JavaScript?

Enhanced_Backend.php => Line: 98

The type attribute is unnecessary for JavaScript resources.

Source: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-type

**Comment by DorsetDigital** [comment]
Yeah, that's just inherited from the default backend..  I've never been entirely sure why it's in there!
Simple enough to remove.
